name: "Build Python"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize

    
jobs:
  
  build-python:

    name: "build python"
    runs-on: "ubuntu-22.04"

    steps:
      - name: checkout
        # https://github.com/actions/checkout/releases/tag/v4.0.0
        uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2

      - name: setup-python
        # https://github.com/actions/setup-python/releases/tag/v5.1.0
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
        with:
          python-version-file: "/.python-version"  

      - name: install-py-deps
        run: pip3 install --require-hashes --requirement requirements-output.txt

  build-python-cert-diff:

    name: "build python cert diff"
    runs-on: "ubuntu-22.04"

    steps:
      - name: checkout
        # https://github.com/actions/checkout/releases/tag/v4.0.0
        uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2

      - name: setup-python
        # https://github.com/actions/setup-python/releases/tag/v5.1.0
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
        with:
          python-version-file: "/.python-version"  

      - name: install-py-deps
        run: pip3 install --require-hashes --requirement requirements-cert-diff.txt   

           

      